#!/bin/bash
#
clear

case "$#" in
	0 )
		echo "usage: testmode [start | stop]"
		echo "    or testmode [on | off]"
	;;
esac


case "$1" in
	'start' | 'on')
		echo killing all node procs
		killall node
		rm /tmp/data/gotResults.json

		set -e;
		cd src;
		mocha --recursive;
		cd ..
   		echo "Starting local webServer and smartMeter in test mode..."
		./src/main/webServer/webServer.js > /tmp/webServer.log 2>&1 &
		./src/main/meter/smartMeter.js  > /tmp/smartMeter.log 2>&1 &
		./src/main/meter/smartMeterSimulator.js  > /dev/null 2>&1 &
		exit 0
	;;

	'stop' | 'off' )
		clear
		echo killing all node procs
		killall node
		exit 0
	;;
esac