#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          smartMeter
# Required-Start:    $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Stop:     $remote_fs $syslog
### END INIT INFO


WPATH=/home/pi/production/smartMeter/
RCPATH=/home/pi/production/smartMeter/src/main/meter/
SERVER=src/main/meter/smartMeter.js
SERVERPATH=$WPATH$SERVER
RCDSERVER=rcdSmartMeter

case "$1" in
'start')
mypids=$(ps -ef | grep $SERVER | grep -v "grep" | wc -l)
if [ $mypids -gt 0 ]
then
	echo there is $mypids $SERVER running
	echo `ps -ef | grep $SERVER | grep -v grep`
else
	(cd $WPATH; node $SERVER ) > /tmp/smartMeter.log 2>&1 &
	echo started $SERVER
	logger "started $SERVER"
fi
;;

'stop')
echo "Stoping smartMeter ..."
for ps in `ps -ef | grep $SERVER | grep -v grep | awk '{print $2}'`
do
	echo 'found $SERVER in process '$ps'. Now kill it...'
	kill -9 $ps
	logger "killed $SERVER"
	echo done
done
;;

'restart')
$0 stop
$0 start
;;

'rcinstall')
    echo "installing $WPATH$RCDSERVER in /etc/init.d/."
    logger "installing $WPATH$RCDSERVER in /etc/init.d/."
	sudo cp $RCPATH$RCDSERVER /etc/init.d/.
    sudo update-rc.d -f $RCDSERVER remove
	sudo update-rc.d -f $RCDSERVER defaults
;;

'Required-Stop')
;;

'force-reload')
;;

'status')
    mypids=$(ps -ef | grep $SERVER | grep -v "grep" | wc -l)
    echo there is $mypids $SERVER running
    ;;

esac

exit 0